import type { Metadata } from "next";
import "./globals.css";
import SideBar from "@/components/side-bar";
import Header from "@/components/header";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <div className="h-screen grid grid-rows-[auto_1fr] grid-cols-12 overflow-hidden">
                    <div className="h-full col-start-1 col-end-3 row-span-full overflow-y-auto">
                        <SideBar />
                    </div>
                    <div className="col-start-3 col-span-full">
                        <Header />
                    </div>
                    <main className="col-start-3 col-span-full overflow-auto bg-yellow-500">
                        {children}
                    </main>
                </div>
            </body>
        </html>
    );
}
